MCR_REGISTER_COMPSID( GOC_Type_Hero )
MCR_REGISTER_COMPSID( GOC_Type_Floor )
MCR_REGISTER_COMPSID( GOC_Type_Button1 )
MCR_REGISTER_COMPSID( GOC_Type_Wall )
MCR_REGISTER_COMPSID( GOC_Type_Wall_Selectable )


//temp remove once gameplay start
MCR_REGISTER_COMPSID( GOC_Type_CUBE )
MCR_REGISTER_COMPSID( GOC_Type_NONROTATINGCUBE )
MCR_REGISTER_COMPSID( GOC_Type_SPHERE )
MCR_REGISTER_COMPSID( GOC_Type_GROUNDTEXTURE )
MCR_REGISTER_COMPSID( GOC_Type_SCRIPT )