MCR_REGISTER_COMPSID( GOC_Type_Hero )
MCR_REGISTER_COMPSID( GOC_Type_Cube )
MCR_REGISTER_COMPSID( GOC_Type_Gun )
MCR_REGISTER_COMPSID( GOC_Type_Floor )
MCR_REGISTER_COMPSID( GOC_Type_Button1 )
MCR_REGISTER_COMPSID( GOC_Type_Button2 )
MCR_REGISTER_COMPSID( GOC_Type_Button3)
MCR_REGISTER_COMPSID( GOC_Type_Door1 )
MCR_REGISTER_COMPSID( GOC_Type_Wall )
MCR_REGISTER_COMPSID( GOC_Type_Ceiling )
MCR_REGISTER_COMPSID( GOC_Type_Wall_Selectable )
MCR_REGISTER_COMPSID( GOC_Type_Conv_Belt )
MCR_REGISTER_COMPSID( GOC_Type_Laser )
MCR_REGISTER_COMPSID( GOC_Type_Destroyer )
MCR_REGISTER_COMPSID( GOC_Type_Cube_Thrower )
MCR_REGISTER_COMPSID( GOC_Type_Sphere_Thrower )
MCR_REGISTER_COMPSID( GOC_Type_Cube_Thrower_Periodic )
MCR_REGISTER_COMPSID( GOC_Type_TransparentWall )
MCR_REGISTER_COMPSID( GOC_Type_VerticalSlider )
MCR_REGISTER_COMPSID( GOC_Type_RotatingSlider )
MCR_REGISTER_COMPSID( GOC_Type_RotatingSlider1 )
MCR_REGISTER_COMPSID( GOC_Type_Ramp )
MCR_REGISTER_COMPSID( GOC_Type_CollisionBox )
MCR_REGISTER_COMPSID( GOC_Type_CollisionSphere )
//MCR_REGISTER_COMPSID( GOC_Type_Teleporter )
MCR_REGISTER_COMPSID( GOC_Type_Domino )
MCR_REGISTER_COMPSID( GOC_Type_Sphere )
MCR_REGISTER_COMPSID( GOC_Type_Constraint )
MCR_REGISTER_COMPSID( GOC_Type_BridgeRigid )
MCR_REGISTER_COMPSID( GOC_Type_RotatingSword )
MCR_REGISTER_COMPSID( GOC_Type_MetalPlate )
MCR_REGISTER_COMPSID( GOC_Type_Rope )
MCR_REGISTER_COMPSID( GOC_Type_HangingBall )
MCR_REGISTER_COMPSID( GOC_Type_RopePoint )
MCR_REGISTER_COMPSID( GOC_Type_RopeKnot )
MCR_REGISTER_COMPSID( GOC_Type_RopePart )
MCR_REGISTER_COMPSID( GOC_Type_LaserBase )
MCR_REGISTER_COMPSID( GOC_Type_TransparrentDominoBase )
MCR_REGISTER_COMPSID( GOC_Type_CanonBall )
MCR_REGISTER_COMPSID( GOC_Type_LightBulb )
MCR_REGISTER_COMPSID( GOC_Type_LightBulbWithMass )
MCR_REGISTER_COMPSID( GOC_Type_TransparrentTube )
MCR_REGISTER_COMPSID( GOC_Type_LaserLight )
MCR_REGISTER_COMPSID( GOC_Type_TimeCancelField )
MCR_REGISTER_COMPSID( GOC_Type_EventTriggerBox )
MCR_REGISTER_COMPSID( GOC_Type_Cylinder )
MCR_REGISTER_COMPSID( GOC_Type_Bullet )
MCR_REGISTER_COMPSID( GOC_Type_Basic )
MCR_REGISTER_COMPSID( GOC_Type_ObjectHolder )
MCR_REGISTER_COMPSID( GOC_Type_ComplexTest )
MCR_REGISTER_COMPSID( GOC_Type_TableTop )
MCR_REGISTER_COMPSID( GOC_Type_TableLeg )
MCR_REGISTER_COMPSID( GOC_Type_CubeTest )
MCR_REGISTER_COMPSID( GOC_Type_RestrictAutoMoving )
MCR_REGISTER_COMPSID( GOC_Type_LightWithoutBulb)
MCR_REGISTER_COMPSID( GOC_Type_LevelBox)
MCR_REGISTER_COMPSID( GOC_Type_CheckPointBox)
MCR_REGISTER_COMPSID( GOC_Type_Hex)
MCR_REGISTER_COMPSID( GOC_Type_FieldBase)
MCR_REGISTER_COMPSID( GOC_Type_CylinderTest)
MCR_REGISTER_COMPSID( GOC_Type_Animation1)
MCR_REGISTER_COMPSID( GOC_Type_CubeST )
MCR_REGISTER_COMPSID( GOC_Type_CubeGlow )
MCR_REGISTER_COMPSID( GOC_Type_ActivationGlowItems)
MCR_REGISTER_COMPSID( GOC_Type_ActivationGlowItems1)
MCR_REGISTER_COMPSID( GOC_Type_Ellipsoid )
MCR_REGISTER_COMPSID( GOC_Type_ConeTest )
MCR_REGISTER_COMPSID( GOC_Type_PillarForButton )
MCR_REGISTER_COMPSID( GOC_Type_PillarForGun )
MCR_REGISTER_COMPSID( GOC_Type_TutorialBox )
MCR_REGISTER_COMPSID( GOC_Type_TableLegWithBody)
MCR_REGISTER_COMPSID( GOC_Type_TableTopWithBody)
MCR_REGISTER_COMPSID( GOC_Type_WallforLava)
MCR_REGISTER_COMPSID( GOC_Type_TeleporterModel)
MCR_REGISTER_COMPSID( GOC_Type_TeleporterEventTrigger)
MCR_REGISTER_COMPSID( GOC_Type_Cake)
MCR_REGISTER_COMPSID( GOC_Type_AnimatedDoor)
MCR_REGISTER_COMPSID( GOC_Type_Sphere_ThrowerTest)
MCR_REGISTER_COMPSID( GOC_Type_WallTest)
MCR_REGISTER_COMPSID( GOC_Type_PillarForButtonTest )
MCR_REGISTER_COMPSID( GOC_Type_ExitLevelBox )











//temp remove once gameplay start

MCR_REGISTER_COMPSID( GOC_Type_NONROTATINGCUBE )

MCR_REGISTER_COMPSID( GOC_Type_QUAD )


//DEBUG
MCR_REGISTER_COMPSID( GOC_Type_DebugCube )
MCR_REGISTER_COMPSID( GOC_Type_DebugSphere )
MCR_REGISTER_COMPSID( GOC_Type_NOTHING )//for objects like the arrows etc





//ALHPABET
MCR_REGISTER_COMPSID( GOC_Type_LetterA )
MCR_REGISTER_COMPSID( GOC_Type_LetterB )
MCR_REGISTER_COMPSID( GOC_Type_LetterC )
MCR_REGISTER_COMPSID( GOC_Type_LetterD )
MCR_REGISTER_COMPSID( GOC_Type_LetterE )
MCR_REGISTER_COMPSID( GOC_Type_LetterF )
MCR_REGISTER_COMPSID( GOC_Type_LetterG )
MCR_REGISTER_COMPSID( GOC_Type_LetterH )
MCR_REGISTER_COMPSID( GOC_Type_LetterI)
MCR_REGISTER_COMPSID( GOC_Type_LetterJ )
MCR_REGISTER_COMPSID( GOC_Type_LetterK )
MCR_REGISTER_COMPSID( GOC_Type_LetterL )
MCR_REGISTER_COMPSID( GOC_Type_LetterM )
MCR_REGISTER_COMPSID( GOC_Type_LetterO )
MCR_REGISTER_COMPSID( GOC_Type_LetterP )
MCR_REGISTER_COMPSID( GOC_Type_LetterQ )
MCR_REGISTER_COMPSID( GOC_Type_LetterR )
MCR_REGISTER_COMPSID( GOC_Type_LetterS )
MCR_REGISTER_COMPSID( GOC_Type_LetterT )
MCR_REGISTER_COMPSID( GOC_Type_LetterU )
MCR_REGISTER_COMPSID( GOC_Type_LetterV )
MCR_REGISTER_COMPSID( GOC_Type_LetterW )
MCR_REGISTER_COMPSID( GOC_Type_LetterX )
MCR_REGISTER_COMPSID( GOC_Type_LetterY )
MCR_REGISTER_COMPSID( GOC_Type_LetterZ )

MCR_REGISTER_COMPSID( GOC_Type_LetterTforExit )
MCR_REGISTER_COMPSID( GOC_Type_LetterIforExit)
MCR_REGISTER_COMPSID( GOC_Type_LetterXforExit )
MCR_REGISTER_COMPSID( GOC_Type_LetterEforExit )











